[general]
live_config_reload = true

[window]
decorations = "buttonless"
dynamic_title = false
# opacity = 1
opacity = 0.93
blur = true
option_as_alt = "Both"
startup_mode = "Maximized"

[window.padding]
x = 15
y = 15

[font]
# size = 13
# normal = { family = "CommitMonoLight" , style = "Regular" }
# bold = {style = "Bold"}

# size = 12.8
# normal = { family = "Hermit" , style = "Light" }
# bold = {style = "Bold"}

# size = 13
# normal = { family = "Reddit Mono" , style = "Light" }
# bold = {style = "SemiBold"}

# size = 13
# normal = { family = "Kode Mono" , style = "Regular" }
# bold = {style = "SemiBold"}

# size = 13.5
# normal = { family = "Sono Monospace" , style = "Light" }
# bold = {style = "SemiBold"}

# size = 13
# normal = { family = "Metrickal" , style = "Regular" }

# size = 16
# normal = { family = "Courier Prime Code" , style = "Regular" }

# size = 13.8
# normal = { family = "Google Sans Mono" , style = "Regular" }
# bold = {style = "SemiBold"}

# size = 13.5
# normal = { family = "Iosevka Term" , style = "Light Extended" }
# bold = {style = "SemiBold Extended"}

# size = 14.5
# normal = { family = "Iosevka Term" , style = "Light" }
# bold = {style = "SemiBold"}

# size = 13.2
# normal = { family = "Source Code Pro" , style = "Regular" }

# size = 13.8
# normal = {style = "Light", family = "Geist Mono"}
# bold = {style = "Medium"}

# size = 14.8
# normal = {family = "JetBrains Mono", style = "Light" }
# bold = {style = "Medium"}

# size = 13.8
# normal = {family = "Overpass Mono", style = "Light" }
# bold = {style = "SemiBold"}

# size = 14
# normal = {family = "PT Mono", style = "Regular" }
# bold = {style = "Bold"}


# size = 11.8
# normal = {family = "Martian Mono", style = "Std xLt" }
# bold = {style = "Std Rg"}

# size = 14.8
# normal = {family = "Cascadia Code", style = "Light" }
# bold = {style = "SemiBold"}

size = 16
normal = {family = "mononoki", style = "Regular" }

# size = 14
# normal = {family = "Fira Code", style = "Regular" }
# bold = {style = "SemiBold"}

# size = 17
# normal = {style = "Regular", family = "Fantasque Sans Mono"}
# bold = {style = "Bold"}

# size = 13
# normal = {style = "Regular", family = "Menlo"}
# bold = {style = "Bold"}

# size = 12.8
# # normal = {style = "Regular", family = "SF Mono"}
# normal = {style = "Light", family = "SF Mono"}
# bold = {style = "Medium"}

# size = 13.5
# normal = {family = "IBM Plex Mono", style = "Regular" }
# bold = {style = "SemiBold"}

# size = 15
# normal = {family = "Andale Mono", style = "Regular" }
# bold = {style = "SemiBold"}

# family = "Martian Mono"
# family = "Iosevka Fixed"
# family = "Mononoki"
# family = "Andale Mono"
# family = "Cascadia Code"
# family = "Fira Code"
# family = "Google Sans Mono"
# family = "M PLUS 1 Code"


[colors.bright]
black = "#475258"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.cursor]
cursor = "#E3DF68"
text = "#000000"

[colors.normal]
black = "#414b50"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.primary]
background = "#272e33"
foreground = "#d3c6aa"

[cursor]
blink_interval = 750
thickness = 0.25
unfocused_hollow = true

[cursor.style]
blinking = "Off"
shape = "Block"

# [debug]
# log_level = "Debug"


[[hints.enabled]]
command = "open"
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`\\(\\)]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "Command"

[[hints.enabled]]
regex = '([A-Z]|[a-z])+-\d+'

[hints.enabled.binding]
key = "J"
mods = "Control|Shift"

[hints.enabled.command]
args = ["-c", "open \"https://woltwide.atlassian.net/browse/${0:-}\""]
program = "bash"

[hints.enabled.mouse]
enabled = true
mods = "Command"

[mouse]
hide_when_typing = true
