# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ANTIBODY_HOME=~/.zsh/plugins
source <(antibody init)
antibody bundle < ~/.zsh/plugins.txt

for file in ~/.zsh/*.zsh; do
        source $file
done

# vim mode
bindkey -v
bindkey -M viins '^?' backward-delete-char
bindkey -M viins '^H' backward-delete-char
bindkey -M viins '^P' up-history
bindkey "^I" fzf-completion
bindkey "^R" fzf-history-widget
bindkey "^T" fzf-file-widget
bindkey "^[c" fzf-cd-widget
bindkey -M viins '^N' down-history

setopt share_history

PATH=$PATH:~/.zsh/scripts
source ~/.profile
