# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ANTIBODY_HOME=~/.zsh/plugins
source <(antibody init)
antibody bundle < ~/.zsh/plugins.txt

for file in ~/.zsh/*.zsh; do
        source $file
done
wait

HISTFILE="$HOME/.zsh_history"
HISTSIZE=100000000
SAVEHIST=100000000
setopt share_history

export KEYTIMEOUT=2 # 20ms
KEYTIMEOUT=2

# vim mode
bindkey -v
# bindkey -M viins '^?' backward-delete-char
bindkey -M viins '^H' backward-delete-char
bindkey -M viins '^P' up-history
bindkey -M viins '^N' down-history
bindkey -M viins "^?" backward-delete-char
bindkey "^I" fzf-completion
bindkey "^R" fzf-history-widget
bindkey "^T" fzf-file-widget
bindkey "^[c" fzf-cd-widget

bindkey "^W" backward-kill-word
bindkey "^H" backward-delete-char      # Control-h also deletes the previous char
bindkey "^U" backward-kill-line

# help
unalias run-help
autoload run-help
alias help=run-help

# PATH
PATH=$PATH:~/.zsh/scripts
PATH=$PATH:~/.local/bin
source ~/.profile
