# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ANTIBODY_HOME=~/.zsh/plugins
source <(antibody init)
antibody bundle < ~/.zsh/plugins.txt

for file in ~/.zsh/*.zsh; do
  source $file
done

source ~/.profile
