# defaults write -g NSWindowShouldDragOnGesture -bool true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

automatically-unhide-macos-hidden-apps = true

after-startup-command = ['fullscreen']
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

accordion-padding = 50

[gaps]
inner.horizontal = 0
inner.vertical =   0
outer.left =       [{ monitor."^built-in" = 0 }, 400]
outer.bottom =     0
outer.top =        0
outer.right =      [{ monitor."^built-in" = 0 }, 400]

[mode.main.binding]
alt-comma = 'reload-config'

alt-h = 'focus --boundaries-action wrap-around-the-workspace left'
alt-j = 'focus --boundaries-action wrap-around-the-workspace down'
alt-k = 'focus --boundaries-action wrap-around-the-workspace up'
alt-l = 'focus --boundaries-action wrap-around-the-workspace right'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

# alt-b = 'workspace B'
# alt-t = 'workspace T'
alt-u = 'workspace U'
alt-i = 'workspace I'
alt-o = 'workspace O'
alt-p = 'workspace P'

# alt-shift-b = 'move-node-to-workspace B'
# alt-shift-t = 'move-node-to-workspace T'
alt-shift-u = 'move-node-to-workspace U'
alt-shift-i = 'move-node-to-workspace I'
alt-shift-o = 'move-node-to-workspace O'
alt-shift-p = 'move-node-to-workspace P'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Consider using 'join-with' command as a 'split' replacement if you want to enable
# normalizations
# alt-shift-s = 'split horizontal'
# alt-shift-v = 'split vertical'

alt-shift-f = 'fullscreen'
alt-shift-w = 'fullscreen --no-outer-gaps'

alt-shift-e = 'layout tiles horizontal vertical'
alt-shift-v = 'layout h_accordion'
alt-shift-s = 'layout v_accordion'
# alt-shift-s = 'layout v_accordion' # 'layout stacking' in i3
# alt-shift-v = 'layout h_accordion' # 'layout tabbed' in i3

alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'

alt-shift-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
# enter = 'mode main'
esc = 'mode main'

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
if.window-title-regex-substring = 'Picture-in-Picture'
run = 'layout floating'
# check-further-callbacks = true
