#!/usr/bin/env bash

set -e -o pipefail

go list -f '{{if not (or .Main .Indirect)}}{{.}}{{end}}' -m -mod=mod all | while read -r name ver; do
	go list -m -mod=mod -u "$name" | ( read -r name old new; [[ -n "$new" ]] && go get -v "$name@latest" || true )
done
